version: '3.4'

services:
  mu.identity:
    env_file: MU.Common/Common.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true
    ports:
      - "5001:80"
    restart: on-failure
    depends_on:
      - mu.data
    networks: 
        - manga-updates-network

  mu.publishers:
    env_file: MU.Common/Common.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PublishersDb;User Id=sa;Password=yourStrongPassword12!@;MultipleActiveResultSets=true
    restart: on-failure
    ports:
      - "5002:80"
    networks: 
        - manga-updates-network

  mu.translators:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
    networks: 
        - manga-updates-network

  mu.data:
    ports: 
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=yourStrongPassword12!@
    volumes: 
        - sqldata:/var/opt/mssql 
    networks: 
        - manga-updates-network

  mu.messages:
    ports:
        - "15672:15672"
        - "5672:5672"
    hostname: "rabbitmq"
    environment:
        - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    networks: 
        - manga-updates-network