version: '3.4'

services:
  mu.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  mu.publishers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"


  mu.translators:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

